### ISSUE TITLE
el6 %install is broken

### ISSUE THREAD

**Issue by bstrad** [aws/ec2-net-utils#3]
https://github.com/aws/ec2-net-utils/blob/b3c52c668d7f205d146ad2b8ff9775db2bc9d745/ec2-net-utils.spec#L80

Should be:
install -d -m755 ~~$RPM_BUILD_ROOT~~$RPM_BUILD_ROOT%{_sysconfdir}/init

**Comment by fred-lefebvre** [comment]
Thanks for reporting this issue.  Your report escaped our attention at the time. This has now been fixed in https://github.com/aws/ec2-net-utils/commit/9bc84e74f537e1c2d18c94b0b219eb9fb911d7ff
