### ISSUE TITLE
DHClient uses default timeout of 60 seconds

### ISSUE THREAD

**Issue by dinusX** [aws/ec2-net-utils#4]
https://github.com/aws/ec2-net-utils/blob/b3c52c668d7f205d146ad2b8ff9775db2bc9d745/ec2net-functions#L201-L203

Could you please set a higher timeout in the dhclient config. Ex: 300s.
The default timeout on AMZN linux for eth0 is 300s.

```bash
$ sudo cat /etc/dhcp/dhclient.conf
timeout 300;
```

When attaching ENI interfaces for large VPCs the DHCP discovery might take a long time (more than 60s) and as a result the kernel routing table is not updated properly.

**Comment by fred-lefebvre** [comment]
This has been addressed in 1.2.2.1
