### ISSUE TITLE
Please provide support for IMDSv2

### ISSUE THREAD

**Issue by awsmiev** [aws/ec2-net-utils#6]
The file "ec2net-functions" calls the metadata service endpoint using cURL to fetch various network interface settings (see lines 36 and 60).

This method is not compatible with servers configured to require HTTP tokens (i.e. IMDSv2 only mode).  Please fetch an API token and add that as a header.  For more information on IMDSv2 please see: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

**Comment by CPCJ79** [comment]
I have submitted a PR adding the metadata_token functionality.  It is pending review https://github.com/aws/ec2-net-utils/pull/7

**Comment by fred-lefebvre** [comment]
Thanks for reporting this. This has been addressed in version 1.3 : https://github.com/aws/ec2-net-utils/commit/be8a53089e50b705cc33a0029f45fa7bfe7a5cf8
